### ISSUE TITLE
Map - highlight the pin when zoom-to-location 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#1020]
Clicking on the "Take Me To My Club" button(1st screencap) or "Vancouver"(2nd screencap) triggers the "zoom-to-location" function(3rd screencap).  However, it is not super easy to spot the pin the Club is located at if the map has more than 1 pin in the viewport.  I wonder if there's a way we can highlight that pin? or maybe we should launch the info popup as when we zoom-to-location.

---
1st
![screen shot 2015-06-10 at 5 15 49 pm](https://cloud.githubusercontent.com/assets/2896608/8097244/a94654d6-0f94-11e5-9252-02ef11a59147.png)
---
2nd
![screen shot 2015-06-10 at 5 16 34 pm](https://cloud.githubusercontent.com/assets/2896608/8097246/b127623a-0f94-11e5-8e12-f383e96254c0.png)
---
3rd
![screen shot 2015-06-10 at 5 16 11 pm](https://cloud.githubusercontent.com/assets/2896608/8097266/fcc2027c-0f94-11e5-8acc-dffe47a7dbd0.png)

**Comment by toolness** [comment]
Ah, yeah, I actually tried adding this way back when implementing the original "add a club" flow, but the [markercluster](https://github.com/Leaflet/Leaflet.markercluster) plugin actually made it quite non-trivial, because the club pop-up doesn't actually *exist* until the map is zoomed-in enough to show the marker (instead of a "cluster" marker that represents a group of markers).

I think this means that we actually have to "adaptively" zoom-in to the user's club location until the marker has appeared, at which point we can open its pop-up...

**Comment by alicoding** [comment]
wondering if this is an issue or if we want to get this implemented?

**Comment by hannahkane** [comment]
Closing most Clubs-related tickets, as we are likely going to build out a pan-Mozilla Clubs platform at some point.
