### ISSUE TITLE
Improve clubs list

### ISSUE THREAD

**Issue by kristinashu** [mozilla/learning.mozilla.org#1422]
https://teach.mozilla.org/clubs/
I don't think this is working very well right now. Perhaps 'See the full list' should expand open on the current page rather than opening a new page. 

<img width="1051" alt="screen shot 2015-11-16 at 4 55 38 pm" src="https://cloud.githubusercontent.com/assets/1068783/11199535/30610374-8c83-11e5-9dfb-9be3d781e87f.png">

https://teach.mozilla.org/clubs/list/
The list is also very long. Maybe the names should be in accordions so we just see the names and then click on one to expand the content.

<img width="1047" alt="screen shot 2015-11-16 at 4 55 48 pm" src="https://cloud.githubusercontent.com/assets/1068783/11199536/307475e4-8c83-11e5-9160-37d326b10bfe.png">

**Comment by hannahkane** [comment]
Thanks for filing this ticket. This was always meant to be a stop-gap solution, in advance of the full Directory, but since that is on temporary pause, I agree it would be good to invest in this page a bit.

Some additional ideas:
 - [ ] Provide filters. e.g. Could we let people filter the list by continent, region, and/or country?
 - [ ] Provide alternate sorting - by date added
 - [ ] For a list this long, I think it's probably better to have the sorting span both columns, so rather than having A-M in the first column, and M-Z in the second column, A-M would be the top half, and N-Z would be the bottom half
 - [ ] Provide a search
