### ISSUE TITLE
Design changes to Clubs page

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1605]
Design is here: https://redpen.io/kn68b61855dcda9ff9 

Note the following changes in addition to what's represented in the redpen:
 - [ ] Pledge copy has changed (noted in a comment on the redpen)
 - [ ] Will be building a [page for Regional Coordinator bios](https://github.com/mozilla/teach.mozilla.org/issues/1815). Will need to provide an IA solution for this
 - [ ] We should also link to the Event Reporter tool. 

Needs discussion of how to implement parts of this with the CMS - i.e. Resources list and FAQs are likely to need regular updates from staff.

**Comment by hannahkane** [comment]
This is no longer blocked, so putting into current milestone as a P2.

**Comment by hannahkane** [comment]
Question about IA: how to handle site sections that have a lot of content like this? Do we have multiple pages? Tabs? Look at other models - e.g. Science site.

Clubs has a lot of content that's not on the site right now.

**Comment by xmatthewx** [comment]
Discussion on secondary and tertiary nav here: https://github.com/MozillaFoundation/Design/issues/163

**Comment by xmatthewx** [comment]
As we discussed during kickoff, we'll focus on the checklist items up top. Revised nav and IA will need to wait for a future heartbeat. cc @sabrinang

**Comment by xmatthewx** [comment]
😄

**Comment by sabrinang** [comment]
Just chatted with @Carotejada about Clubs content https://docs.google.com/document/d/1qf2OOnUqyVjqXU0ivs1RiCGNNf6J8IuKM2AE8U8__as/edit?ts=572a40e4 and there is quite a bit to sift through and get in shape before jumping into design updates. I will work through the doc and propose content/copy structure to get that in place first before proceeding.

**Comment by sabrinang** [comment]
The idea is to structure the clubs page content into 3 tabs (redpen here: https://redpen.io/hud7ccb99dcec62232). 
- Tab 1 is for about Mozilla Clubs content (revising what we have live now)
- Tab 2 is for about club captain and regional coordinator content (the page that Amira is working on?)
- Tab 3 is for Mozilla Club resources content (surfacing spreadsheet content: https://docs.google.com/spreadsheets/d/1dpU02AiN2otBuN0W4Xt9cbIDMpBd3jKKLPs_1QsxeQo/edit#gid=0)

There is some placeholder content but I am structured content on that clubs doc (page 3 onwards) : https://docs.google.com/a/mozilla.com/document/d/1qf2OOnUqyVjqXU0ivs1RiCGNNf6J8IuKM2AE8U8__as/edit?usp=sharing

Not sure if we need a 4th tab to surface current clubs like the clubs list: https://learning.mozilla.org/clubs/list/ but it is something to consider since that page isn’t well connected back to clubs page.

I am unsure overall how we accommodate localization on the learning site but 
there are concerns about how we can surface localized club guides (long list on resources tab as interim solution?).

**Comment by sabrinang** [comment]
Update: @Carotejada and I went over the [google doc](https://docs.google.com/document/d/1qf2OOnUqyVjqXU0ivs1RiCGNNf6J8IuKM2AE8U8__as/edit?ts=572a40e4#heading=h.de39mw1rebuv) and the proposed structure is shaping up. 

Next steps for @Carotejada is to go over doc and fill in missing content and mentioned that @KGorr may be able to assist here too. 

Next steps for me is to create: 
- images of an overview structure of the club network and structure of a club (on Clubs main page)
- mockup layout of how a featured content block appears (on Clubs main page) and how 3 featured resources appears (on Resources page) 
- coordinate with @amirad on "captain and coordinator" tab layout since she has started this work for RC bios there may be a lot of overlap so we should figure out how to proceed with a mockup
- mockup possible 4th tab for Clubs list

Other things to consider:
- after resources content is organized in groups consider what possible sorting function is appropriate to include in mockup and consult a dev if implementation is possible (like [science resources] section filters (https://redpen.io/dr1a6e5c79b466e524))
- also consider filtering capabilities for Clubs list and RC bios (like [science members](https://redpen.io/pq5fb24849ad3b7634)) and what is useful to sort by

**Comment by hannahkane** [comment]
Thanks, @sabrinang and @carotejada.

Flagging @simonwex because this work is surfacing a lot of similarities with the Science site, where similar content (Study Groups, Resources) is structured content in a database, rather than staff-editable CMS pages. I think we might want to consider changing our technical approach to the Clubs pages based on this.

**Comment by amirad** [comment]
The proposed structure looks great! As I'm traveling @KGorr is helping out with the RC bios

**Comment by KGorr** [comment]
This all looks great to me, nice work everyone. I am working to get the RC bios by next Wednesday, May 18th. If I can help with anything else, please let me know!

**Comment by Carotejada** [comment]
Right @amirad  & @KGorr ? The design team is awesome :)

@KGorr I'm putting together all the content we currently have and will share it with you first thing next Tuesday 17th.

We wish you can help us editing and suggesting even more cool copy :)

**Comment by KGorr** [comment]
@Carotejada - happy to help! Looking forward to seeing it.

**Comment by sabrinang** [comment]
Updates for layout ideas on redpen https://redpen.io/pbcb2eda696626f5e7:
- have the description on the banner
- we can use 3 small line art graphics to describe club network, club structure and club captions
- after some consideration and chatting to @hannahkane we can organize tabs by:
    - tab 1 to focus on introducing/explaining clubs and captains to new people with call to action to apply
    - tab 2 dives deeper on details on clubs and more information to those who are already interested 
    - tab 3 club resources

This is mainly because on the first page when we introduce clubs and ask people to apply there wasn't context on what a captain is and how applying to become a captain relates to clubs system. @Carotejada what do you think about arrangement in the [redpen](https://redpen.io/pbcb2eda696626f5e7)?

**Comment by hannahkane** [comment]
Thanks for this iteration, @sabrinang.

Looking at it, I'm wondering if this variation might work better:
 * Tab 1: About Mozilla Clubs - 3 point Clubs diagram, featured updates, map
 * Tab 2: Start a Club - all of the info about why/how to apply to be a Club Captain + start of application process
 * Tab 3: Running Your Club - all of the resources/info for people who are actively running a Club: resource list (perhaps with an accordion), FAQ, office hours, links to Regional Coordinators page, Event Reporter, Training Course, and App

@sabrinang @Carotejada — what do you think of that structure?

**Comment by amirad** [comment]
Could these in tab 3 be in tab 2 instead? FAQ, office hours, links to Regional Coordinators page.

Also the new Mozilla Clubs App is *only* for our 20 clubs in Cape Town and Nairobi so not public to share or for anyone to join. Thus, we won't be able to share it on the site and others.

**Comment by hannahkane** [comment]
What do you see as the advantage to combining them? I think tab 2 and tab 3 are serving different purposes (in the model I suggested two comments up). The goal of tab 2 is to get people to apply to be a CC, whereas the goal of tab 3 is to support existing CCs. I think it makes sense to separate them, but curious to know your thoughts.

**Comment by Carotejada** [comment]
Thanks for this @sabrinang and @hannahkane. I'm a bit confused with the last changes on the structure of contents. Can you share more info about the purpose of each category in this new structure? 

This is what I see now: 

The **first tab** which was designed to provide general info about clubs is now specific for Captains. 

The **second tab** which was specific info for CC and RC, now includes diverse info about clubs, some resources, and FAQ. 

The **third tab** didn't change, it still contains exclusively resources for clubs.

**Comment by hannahkane** [comment]
@Carotejada - sorry this is confusing! @sabrinang made some edits based on a conversation she and I had. The [redpen](https://redpen.io/pbcb2eda696626f5e7) reflects those edits, which are described in her comment [here](https://github.com/mozilla/learning.mozilla.org/issues/1605#issuecomment-219481084).

What I was describing in [this comment](https://github.com/mozilla/learning.mozilla.org/issues/1605#issuecomment-219561706) is a suggested next variation (no redpen for that yet).

Overall, what I'd like to do is have a *single purpose* and *defined audience* for each tab. So, for my suggested variation, I'm trying to move us towards something like this:

* Tab 1 
  * Purpose: explain what the Mozilla Clubs program is
  * Audience: curious person, potential partner
* Tab 2
  * Purpose: inspire people to apply to be CCs
  * Audience: potential CCs
* Tab 3
  * Purpose: support current CCs
  * Audience: active CCs

**Comment by Carotejada** [comment]
Oh, got it! I like this variation.

**Comment by sabrinang** [comment]
Updated About Mozilla Clubs, Start a Club and Running Your Club tab layouts on redpen: https://redpen.io/p/rb14e4c0eb3594f430

**Comment by hannahkane** [comment]
Nice, @sabrinang. This is really starting to make sense to me! What do you think, @Carotejada?

I left some comments about the specific content and the hierarchy.

**Comment by KGorr** [comment]
Hello team. The RCs are still scrambling to update their tabs, so I allowed them until the end of the day today (Pacific Time) to get everything to me. I'll QC them tomorrow morning and will send to you then, @hannahkane. What is the best way to transfer the images over? Most attached an image to an email.

**Comment by KGorr** [comment]
Also, if it helps for planning purposes, I currently have 6 ready-to-go RC bios. Will likely get a few more today.

**Comment by Carotejada** [comment]
Looking good @hannahkane  and @sabrinang 
I feel this structure works well. The purpose of each tab (category) is clear and logic. 

We´ll move forward with content based on this distribution and will share it with you to make final adjustments.

@KGorr thanks for your help putting together RC bios!

**Comment by KGorr** [comment]
You can find the bios [here](https://docs.google.com/a/mozilla.com/document/d/16NWLHU5CAYEUucUOkb689QHYyEI--ulg5j8V7MQm4_8/edit?usp=sharing). (There may be 1 more coming in today, I'll add it if it's not too late) Please let me know if anything needs adjusted. I have all of the images in emails, please let me know how you'd like them passed along. Thanks!

**Comment by Carotejada** [comment]
Súper! Thanks @KGorr

**Comment by amirad** [comment]
Thanks @KGorr Added another bio I had and did some editing in the doc. Let's move forward with the six we have? With the CRM process we should be able to add the other ones easily afterwards right @hannahkane

**Comment by KGorr** [comment]
No problem. There are actually 12 bios in the doc (like I said...lots of folks scrambled at the last minute to get included!) You reviewed all of them,but just wanted to clarify the number of spots needed for the site. :)

**Comment by hannahkane** [comment]
thanks, @KGorr. Can you email the photos to me, please?

Yes, @amirad, should be easy to edit once we get this in the CMS.

**Comment by hannahkane** [comment]
Blocked on copy

**Comment by hannahkane** [comment]
@Carotejada - do you have an estimate for when you'll have the final copy? @sabrinang will be on PTO after next week, so I'm hoping we can give her several days to finish this before she leaves.

**Comment by Carotejada** [comment]
Hola @hannahkane! We already have a document in which @kgorr @amira @juliav and myself have been contributing.  Since I'm just coming back from DC today after a training week, will have it ready by Monday night.

**Comment by hannahkane** [comment]
Awesome. Thank you, and welcome back! :)

**Comment by sabrinang** [comment]
Thanks for sending clubs copy https://docs.google.com/document/d/1yQgNldfjwGE_lT0JEeTDsgzNJTceWh58i6VsUyishAo/edit# 


I have some feedback for the sections: 

**About Mozilla Clubs Tab**

For an initial placement of the copy (see older redpen: https://redpen.io/pbcb2eda696626f5e7/4), you can see there are a few issues with the density and length of text and should be reduced so we don’t lose the attention of the reader and not overwhelm them as they are starting to learn what clubs are. I’ve included an example of this redpen: https://redpen.io/pbcb2eda696626f5e7 that shows shorter adapted sections of text. Also, the video has dated information on web lit and doesn’t reflect current web lit 2.0 terminology and is off brand so it shouldn’t be included for this iteration.

**Start a Club Tab** (https://redpen.io/hy19242612b482d7ce)

The first title should connect Start a Club tab title to other Club Captain titles better. I find the first title a bit abrupt from expecting to read things about starting a club from the tab title but everything being about Club Captains.

“Why Become a Club Captain” section copy are all quotes/testimonials so it doesn’t really answer why you should become a club captain. The copy can instead includes value proposition and personal benefits for Club Captains that may make a more convincing case. Also, this video is a bit unpolished and off brand and can use some more refinement before being posted.

“How do I become a Club Captain” section step 2 & 3 could be cleaned up since receiving a certificate is a result of completing training but not an additional actionable step in the becoming a club captain process.

The quotes/testimonials can be its own section after the CTA to give them more perspective on what it is like.  

**Running a Club** (https://redpen.io/nw7e55e75c539e6e9f)

We are highlighting the event reporter but needs to be supported with descriptive text that it should be frequently accessed and used by Club Captains.

Since the training course, is integrated in the on boarding process for Captains it doesn’t need to be highlighted in Running your Club resources as it is expected they have completed it already but will still be reference in Club Captain’s Club Guides accordion section.

Please put copy suggestions in the google doc as it is easier to collect that way since redpen comments get lost when new versions are posted. I will continue iterating from your feedback!

**Comment by amirad** [comment]
Adding @jvallera to help project manage from the clubs side!

**Comment by hannahkane** [comment]
I really like the changes you made, @sabrinang. It's much easier to read now. I added more comments directly to the redpen.

**Comment by hannahkane** [comment]
We're still iterating on this, so moving to an upcoming heartbeat to finish.

**Comment by jvallera** [comment]
Thanks @hannahkane the redpen looks great @sabrinang I made edits to the copy in a new document and @Carotejada is currently merging with the copy doc you all have been using. I am happy to be point person to keep this moving while Caro is on PTO after London.

**Comment by sabrinang** [comment]
I have updated the redpen https://redpen.io/p/rb14e4c0eb3594f430 with @jvallera copy updates on gdocs https://docs.google.com/a/mozilla.com/document/d/1yQgNldfjwGE_lT0JEeTDsgzNJTceWh58i6VsUyishAo/edit?usp=sharing 

**Note:** Some of the intro copy paragraphs are appearing quite text heavy than the previous so we may want to consider condensing if possible.

**Comment by hannahkane** [comment]
Thanks, @sabrinang. 

@jvallera - I added some suggestions to the doc about language to potentially cut, for your review.

**Comment by jvallera** [comment]
Thanks @sabrinang and @hannahkane I agree with all of your suggestions. approved them and made edits.

**Comment by sabrinang** [comment]
Changes revised on [gdoc](https://docs.google.com/document/d/1yQgNldfjwGE_lT0JEeTDsgzNJTceWh58i6VsUyishAo/edit#heading=h.l6sn9511s3ur) and [redpen](https://redpen.io/p/rb14e4c0eb3594f430)

**Comment by hannahkane** [comment]
Thanks, @sabrinang. Changes look good.

I think we need to pause on this now for the rest of the heartbeat, to make sure we're addressing other process-oriented work that's in this heartbeat.

**Comment by jvallera** [comment]
Hey @sabrinang I made suggestions on redpen a couple hours ago, but i don't see them in this version. Should add again? or did you already see them? For example, moving "what do club captains think" up and taking out the pic on start a club tab. no worries if not possible, just want to make sure you saw them.

**Comment by amirad** [comment]
This is looking great team! Can't wait to see this live. 
Nice choice of pictures @sabrinang ;) they are all from one city though so would be great if we can mix up a couple with other club locations (rio? elsewhere?)

**Comment by Carotejada** [comment]
![eres-guau-gracias-por-tu-comentario](https://cloud.githubusercontent.com/assets/14875631/16488841/85b3f370-3ea0-11e6-9886-067854554443.gif)

 Thanks for the hard work!

**Comment by sabrinang** [comment]
[Redpen](https://redpen.io/p/rb14e4c0eb3594f430) updated with your suggestions @jvallera (sorry I missed them previously!). 

@amirad  I got the photos from the set Julia shared with me from [Cape Town](https://www.flickr.com/photos/amirad/sets/72157668339120651/with/27064569131/). If you know where I should look for more recent photos or have some favourites to showcase - let me know and I'll be happy to mix up the photo variety!

**Comment by jvallera** [comment]
No worries, thanks @sabrinang here are some additional photo sets: Nairobi https://www.flickr.com/photos/amirad/albums/72157666127395174 and Rio https://www.flickr.com/photos/soapdog/

**Comment by sabrinang** [comment]
implementation ticket here: https://github.com/mozilla/learning.mozilla.org/issues/2013 - closing this ticket
