### ISSUE TITLE
Migrate two community call pages to CMS

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1758]
We need to make both the [Curriculum Workshop](https://teach.mozilla.org/community/curriculum-workshop) and the [MLN Community Call](https://teach.mozilla.org/community/community-call) pages editable in the CMS.

Should also reflect the template changes defined here: https://github.com/mozilla/wp-calypso/issues/29

If we can not do this in the first week of the heartbeat, we'll need to manually accommodate these content requirements:
 * [Curriculum Workshop](https://github.com/mozilla/wp-calypso/issues/36)
 * [Community Call](https://github.com/mozilla/teach.mozilla.org/issues/1752)

**Comment by hannahkane** [comment]
cc @simonwex @mmmavis @gvn @flukeout @vazquez 

Will schedule a time for Monday to discuss a plan for this ticket

**Comment by mmmavis** [comment]
i think there are a few steps needed to be done in order to deliver this (feel free to edit the list below :wink:)

Need to have
- [ ] add mozmaker-templates partial options to Calypso (current status: @mmmavis to wrap up [PR #31](https://github.com/mozilla/wp-calypso/pull/31) and ask @alicoding to review)
- [ ] host Calypso (status: @cadecairos @simonwex could you provide updates? )
- [ ] add ["guide header" and "guide tab"](http://mozilla.github.io/mozmaker-templates/demo/#templates/header-two-tabs) to mozmaker-templates partials (status: is this a WIP already? @vazquez @gvn @flukeout )
- [ ] allow Calypso users to edit sources of the embedded Etherpad / Video (@mmmavis will file a ticket and drop the issue number here)
- [ ] on Teach, rebuild these pages by pulling in the 3 partials together (1 guide header and 2 guide tabs)

Good to have:
- [ ] Add preview functionality , ticket https://github.com/mozilla/wp-calypso/issues/15

**Comment by hannahkane** [comment]
This is likely blocked on the hosting Calypso issue, so @fluekout will move forward on addressing the immediate requirements on the Teach site directly, while we figure out how to resolve the issues Mavis laid out.

**Comment by hannahkane** [comment]
This is blocked on the Calypso hosting issue, I believe. Any more info on that @simonwex?
