### ISSUE TITLE
Complete Credly doc for Mozilla production server

### ISSUE THREAD

**Issue by simonwex** [mozilla/learning.mozilla.org#1771]
We need to fill out the doc for provisioning our production server. We're currently using staging

**Comment by hannahkane** [comment]
@simonwex - is this still on your plate?

**Comment by simonwex** [comment]
I realized I hadn't gotten to this, nor delegated it. I've forwarded the doc to Pomax. If he has any questions, I'm happy to make myself available. – I sent him my cell number.

**Comment by Pomax** [comment]
No real questions for @simonwex, but some questions for @hannahkane  and then some action items we can work on next week:

- [ ] we need a logo image for our credly portal.
- [ ] we probably want a banner image, too. We can have two different ones:
  - one for the login screen
  - one for the moz profile page
- [ ] we need a brief document, or page on MLN that describes our badges program (and isn't the `/badges` page, because that doesn't actually detail much)
- [ ] we'll need to give Credly a link to our style guide so they can set up our instance with the coloring we need.
- [ ] we'll need to give Credly an "about" text. There is an optional "location" but telling the world we're Mozilla, Mountain View, rather than just Mozilla, feels counterproductive. We are a global organisation.
- [ ] we can have linkedin, facebook, and twitter links (not sure if those first two matter)
- [ ] we can tie our own google analytics into our instance by giving credly a UA-xxxxxxxx-x code, so I'm sure this is a thing @adamlofting would like to be appraised of.
- [ ] who should be the main contact that credly contacts for questions around our enterprise instance?

- [ ] we need to decide on an org. name (Mozilla? MLN? Mozilla Foundation? Mozilla Learning?)
- [ ] we need a site title (e.g. "MLN Badges")
- [ ] we need a subdomain name, which is probably tied to our choice in org name (e.g. mozilla.credly.com, mozlearning.credly.com, etc)
- [ ] there is some freedom around the vocabulary, so by default credly uses "Credit" (my credit, etc) and "Badge" (the thing they see on the site), but we can use different words. I don't think we do, though

**Comment by hannahkane** [comment]
Thanks, @Pomax.

cc @anmechung to help with some of the copy requests, and @xmatthewx as a flag for the design/branding-related items.

Let's work on this stuff during the next heartbeat.

**Comment by anmechung** [comment]
@pomax @hannahkane I will definitely help with copy requests

**Comment by xmatthewx** [comment]
It'd be helpful to have some screenshots to see where these logos and banners will reside. 

If we're creating a credly space specifically for MLN implement (at not for Mozilla at-large), then let's use:  
 - Mozilla logo in small spots, Mozilla Learning logotype in banners
 - "Mozilla Learning" as default string
 - If mozilla.credly.com won't raise any concern, I'd favor that. If it does, mozillalearning.credly.com

@hannahkane – Luke or Sabrina can point to appropriate styles used on the Learning site.

**Comment by Pomax** [comment]
@xmatthewx I've forwarded you the setup document that comes with screenshots that illustrate where all our branding would end up, and how many screens are involved. I'd attach it to this issue except as an enterprise setup document I'm pretty sure I'm not at liberty to make it freely accessible =)

**Comment by hannahkane** [comment]
Started a pad to discuss the specifics. Could use initial input on branding from @anmechung, @ldecoursy and/or @chrislarry33: https://public.etherpad-mozilla.org/p/credlydoc

cc @xmatthewx @sabrinang

**Comment by hannahkane** [comment]
Thanks, @anmechung, for your responses on the etherpad. @Pomax - I think we now have answers to everything, though we'll still need a banner image. We can dedicate some time to this after London.

**Comment by Pomax** [comment]
:+1:

**Comment by Pomax** [comment]
@xmatthewx would you have time to help finish this up this week, or might there be someone else available to make sure we finish this up before the next heartbeat?

**Comment by xmatthewx** [comment]
Sure @Pomax. I bet @kristinashu is our best candidate if she isn't swamped with open web fellows. Otherwise, let's meet on Friday to push things thru. (I'm out tomorrow, you on Thursday.)

**Comment by Pomax** [comment]
:+1: let's talk on Friday
