### ISSUE TITLE
Marking a Club as approved should trigger an email

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1826]
This is a new workflow for us, but it would save time for staff. Currently, @KGorr reviews Club applications and manually send both Approval and Rejection emails to Club Captain applicants.

Let's discuss how we can build a workflow that automates the Approval email at least.

**Comment by hannahkane** [comment]
We are unlikely to get to this this heartbeat, given the found work around badges. Moving to next heartbeat.

**Comment by simonwex** [comment]
Hey @Pomax, if you've got questions about django & email, @cadecairos was playing with some of this yesterday.

**Comment by hannahkane** [comment]
Text of email is in [this doc](https://docs.google.com/document/d/14QW2fWrl3LM32EvJV4mbhSCjzR8iPnkattDhrcuF5rE/edit)

**Comment by Pomax** [comment]
we should be able to tie mailing into the model update - if the approval field changes from pending to approved, send mail with test X, if declined, send mail with text Y

**Comment by gideonthomas** [comment]
@KGorr the doc that Hannah has linked above does not contain copy for the rejection email, would you be able to populate that in there?

**Comment by KGorr** [comment]
Happy to do so. @gideonthomas, will there continue to be sub-categories for the denial reason? Just wondering if we will need a couple of variations depending on why they were rejected. 

CC: @jvallera for input

**Comment by gideonthomas** [comment]
yeah, we can totally keep those sub-categories in!

**Comment by KGorr** [comment]
Thinking this through a little more...current sub categories are:

- pending
- approved
- no longer interested
- not qualified
- no response after initial application
- applicant cannot be emailed

Pending needs no email (obviously) and approved is already drafted. No response after initial application isn't needed any longer since the form is a part of the initial application. 

For "applicant cannot be emailed", is there a way for us to know if the email address bounces back? That is the only way we'll know if this subcategory should be selected.

Since we removed a couple of steps with this new form, "no longer interested" will likely not be used since we won't know for awhile if they've fallen off the radar so to speak. 

So, all that to say I think the only one that actually needs a new email drafted is the not qualified field. Although, not being qualified could mean many different things and doesn't happen often. (I denied several as we were working out the kinks on the new form, but only because I never heard back from the CCs to adjust their club name.) Wondering if maybe we should leave the "not qualified" response as a manual process so we can customize and/or ask for application adjustments so that we can approve them. 

Would love your thoughts on all of this, @jvallera.

**Comment by jvallera** [comment]
Thanks @KGorr. I prefer to make the email as automated as possible so here is a suggestion. Maybe the "not qualified" category triggers a general email that includes a list of several possible reasons the club was denied. and we ask them to follow up with us for more information. So we don't waste our time reaching out to people who might be unresponsive. Thoughts?

**Comment by KGorr** [comment]
@jvallera - great idea. I drafted content in the doc above and tagged you in it for input. @gideonthomas - we will let you know once it's approved! Thanks for your patience as we work this out.

**Comment by KGorr** [comment]
@gideonthomas - @jvallera approved the text. Should be good to go now!

**Comment by gideonthomas** [comment]
Thanks @KGorr and @jvallera! I'll incorporate them into the code.
