### ISSUE TITLE
Replace LoFi, NoFi Kit with Offline Icebreakers

### ISSUE THREAD

**Issue by chadsansing** [mozilla/learning.mozilla.org#1881]
@hannahkane, @KGorr, @ldecoursy - the Offline Icebreakers module built from out-of-date LoFi, NoFi materials is ready for review.

**Project for forking**: https://github.com/chadsansing/curriculum-testing/tree/master/offline-icebreakers

**Activities for review**
- https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session01-web-mechanics-speed-dating.html#overview
- https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session02-html-thimble-tag-puzzle.html#overview
- https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session03-puzzles-for-teaching-html.html#overview
- https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session04-a-strong-wind.html#overview
- https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session05-web-literacy-bingo.html#overview
- https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session06-html-puzzle-box.html#overview

**Comment by chadsansing** [comment]
@hannahkane, I can work on a content doc soon, as well, if that'd be handy.

**Comment by hannahkane** [comment]
That would be great. Thanks, @chadsansing!

**Comment by chadsansing** [comment]
Here's the [content doc](https://docs.google.com/document/d/1LtCCvkngU_VRVPAq57pkT72ksZK2Ou7HzRC7fCFKCSY/edit#), @hannahkane.

**Comment by KGorr** [comment]
@chadsansing - here are a few things I caught:

https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session01-web-mechanics-speed-dating.html

Overview
- Suggestion for rewording the 2nd Intro sentence: “Understanding web mechanics helps us protect personal information online, use and understand URLs, IP addresses, search terms, bookmarks and more.”

Preparation
-	1st paragraph typo “machanic”
-	2nd bullet point “toyour” needs space between
-	3rd bullet point: change “content” to “context” and add comma after “web”
-	last bullet point “ont he” needs to be changed to “on the”
-	Last paragraph typo “Asuming” 

Overall – I’m not sure I understand the point of the activity. How are they pretending to be the thing on the card? Are they only supposed to answer the question based on how the "thing" they are pretending to be would answer? Are the questions meant to be answered by the "thing", not by the individual?  I think a few more sentences of explanation would help.

https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session02-html-thimble-tag-puzzle.html

Overview

- Learning Objectives and Material sections are blank

Preparation

-	change first “in” to “on”

Activity

-	“tan” should be “than” in 2nd paragraph
-	A thimble CTA is used, but nothing is linked

Overall – this is the 1st activity I’ve read where we refer to the participants as “kids.” Is that intentional?

https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session03-puzzles-for-teaching-html.html

Overview

-	“Read andParticipate on the Web” subhead needs space between “and” and “participate”
-	Materials section is blank

Preparation

-	3rd paragraph typo “Througought”
-	The 3rd paragraph discusses finding solutions and a puzzle, but nothing has been explained yet
Markup Mixer
-	last sentence needs closing punctuation
-	Mark up is two words in the text but the header is one word

https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session04-a-strong-wind.html

Preparation

-	Punctuation right before the bullets start has both “.” and “:”
-	3rd bullet point “know” needs to be “knows”

Activity

-	“the chance the begin” needs to be” the chance to begin”
It took me a minute to realize what them image was…might be worth swapping out?

https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session05-web-literacy-bingo.html

Preparation

-	web literacy map link has a typo
-	last sentence in the 2nd paragraph needs a space after “<img> and I think the last “for” needs removed

Activity

-	1st paragraph typo “abother”
-	2nd paragraph “someone” needs to be “someones”

Reflection

-	intro to bullets typo “dicussion”
-	1st bullet – remove the extra “your”
-	last bullet typo “onlien”

https://chadsansing.github.io/curriculum-testing/offline-icebreakers/session06-html-puzzle-box.html

Reflection

-	“Web X-Ray Goggles” should be “Mozilla X-Ray Goggles” since web is already used in that sentence
-	3rd paragraph – bold “bonus” (to match the 2nd paragraph) and “a la Markup Mixer.” should be linked to the activity and typo “desccribe”

**Comment by chadsansing** [comment]
Many thanks, @KGorr. "Markup," "marked up," and "mark up" are tricky. I think we're using "markup" correctly as a noun, "marked up" correctly as a past participle, and "mark up" correctly as a verb. Will double check.

**Comment by hannahkane** [comment]
@chadsansing - should I build the landing page and submit a PR now, or should I wait for final versions of the activities themselves?

**Comment by chadsansing** [comment]
@ldecoursy - ready to implement this? cc @hannahkane

**Comment by ldecoursy** [comment]
WFM (that photo for the Thimble Tag Puzzle is cray!)
