### ISSUE TITLE
Create styleguide for badges

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#1899]
We are partnering with another organization to create web literacy badges. In addition to generating the assessment criteria and evidence lists, they also have the capacity to design the actual graphical element for the badge. Can we provide a set of design guidelines and resources so that the badge designs will align with the 21st Century badges we've designed already?

**Comment by hannahkane** [comment]
cc @xmatthewx

**Comment by hannahkane** [comment]
cc @kristinashu

**Comment by kristinashu** [comment]
Here's a quick mockup for colors but I would love to get input from Sabrina.

The blue, orange, purple and yellow used for Problem-Solving, Communication, Creativity and Collaboration won't work as badge background colors since it will be too strongly associated with one of those categories. I'm suggesting we either keep using the green from the old badges or we could use the blue/purple shown below. Then we can use the blue, orange, purple and yellow somewhat randomly for the icon detail.

![colorexploration](https://cloud.githubusercontent.com/assets/1068783/16284914/6c5505f4-3888-11e6-840c-b62c9432db73.jpg)

Here's the working file of this JPG with colors, strokes...: https://drive.google.com/folderview?id=0B2irLVDJivhLbjBGQUhpYUw4QzA&usp=sharing

Also for reference, here is our complete color palette: https://drive.google.com/folderview?id=0B2irLVDJivhLdy0zdVd5N1JETWs&usp=sharing

**Comment by hannahkane** [comment]
Thanks, @kristinashu. I'd prefer to go with the blue, because I think it's useful to differentiate between the different types of badges. I'll share this with our partner organization now, with the caveat that our full design team hasn't had a chance to review this yet, so it may change.

**Comment by kristinashu** [comment]
@sabrinang let us know if you had any other color suggestions

**Comment by sabrinang** [comment]
@kristinashu This is great how you incorporated the web lit colours into the badges and I also like the shade of blue as a base colour as the other lighter colours in the line art work well on it. :+1:

**Comment by anmechung** [comment]
+1!
