### ISSUE TITLE
(August) Design logo for CA.pture project

### ISSUE THREAD

**Issue by simonaramkisson** [mozilla/learning.mozilla.org#1919]
@sabrinang @hannahkane 

Hi Team,

Hive Toronto will be launching a new project called CA.pture and we are in need of a logo that we can put on online documentation, evaluations and our youth council t-shirts. 

This was our last project: http://hivetoronto.org/portfolio/privacybadges/ and we went with Hive colours for the badge logo. 

I am thinking something simple in Hive/Mozilla colours that say CA.pture. Fira font would be awesome.

Let me know if you have any questions.

Simona

**Comment by simonaramkisson** [comment]
Sorry forgot we actually need two logos:

1) CA.pture: Claiming Space for Community Stories

2. CA.pture

**Comment by hannahkane** [comment]
Flagging @xmatthewx since this is about branding.

@simonaramkisson - I want to make sure I understand the request. Do we need a logo, as in some kind of illustration or iconography, or do we just need a wordmark that says CA.pture? Is this something we want to associate with Hive Toronto? If so, I'd advise we use that branding.

Also, do you have a deadline for this?

**Comment by simonaramkisson** [comment]
Awesome. I would say watermark that says Ca.pture and it is associated with Hive Toronto so definitely +1 with that branding. We are just going to capitalize the "C" and keep it as Ca.pture. 

Timeline is September 2016. Just wanted to flag for the team.

**Comment by xmatthewx** [comment]
Rather than a logo, I agree with the suggestion of approaching this as an illustration that appears alongside mozilla/hive branding. Our current and new audiences struggle to understand the relationship between all our various programs and identities, which dilutes our impact. We are working to increase clarity with a more unified identity. This approach will also give you more freedom and flexibility to have fun with the illustration.

@hannahkane – after the h2 roadmap settles, let's take a look to see how this might fit. I'd recommend the deliverable focus on designing a system that could used for initiatives like this one.

**Comment by simonaramkisson** [comment]
This sounds great. I definitely would love it to mirror Mozilla branding so as to show how we are connected. It is a 9 month project which we hope will qualify for renewed funding.

**Comment by hannahkane** [comment]
K. This is in the queue for August. Thanks for giving us so much advance notice, @simonaramkisson!

**Comment by xmatthewx** [comment]
If I understand correctly, @mcdermott415 suggested in [this doc](https://docs.google.com/document/d/1t2rVRlWExhakzAVB1V5TksVWfKUEU3cXIEmOkqVsw3I/edit#) that we pause this work until the Mozilla-wide rebrand lands this fall. I am more than glad to do the project, but believe this is the decision.
