### ISSUE TITLE
Obtain quotes & photos for the new Clubs Pages captain carousel

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2021]
The [designs for the new Clubs Pages](https://redpen.io/hy19242612b482d7ce) include a carousel of testimonials/quotes from some Club Captains. We don't have all of the content for it yet, Caro will assist in collecting it. Let's track that here.

**Comment by hannahkane** [comment]
@carotejada - is there an update on this issue? thanks!

**Comment by Carotejada** [comment]
Hola @hannahkane! I sent them to @flukeout last week ;)

Isisipho
https://www.flickr.com/photos/amirad/27038225402/in/album-72157668339120651/
Club Captain in Africa
“I want to teach the girls how to code. Right now they know the basics but there’s a lot of interest in developing these skills further. Therefore I am working with my school to use study time as an opportunity to hold club activities and events so to have a learning space.”

Patience
https://flic.kr/p/HcgYzw
Club Captain for disabled youth in Africa
"Women with disabilities are particularly vulnerable to being digitally excluded because of the lack of awareness, support, access and cost of equipment. "

Arkodyuti
Club Captain in India
(Picture attached)
"Teaching the web is my passion. The Internet is a catalyst to connectivity. It has made connecting with other humans, places and things faster than any man in the physical world could have ever dreamt of."

Mark
(Picture attached)
Club Captain in Switzerland
"I am excited about providing opportunities for learners to discover and explore an evolving learning landscape. Be the Urban Exploring maker in your school, the Guerrilla technologist, the Graffiti Artist tinkerer. Be ready to provoke & inspire!”

**Comment by hannahkane** [comment]
Cool. Closing this ticket. Thanks!

**Comment by flukeout** [comment]
Thanks again @Carotejada - sorry I forgot to put it in this issue!

**Comment by Carotejada** [comment]
No worries @flukeout 👍
