### ISSUE TITLE
application form followup: determine localisation strategy

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2049]
We need to determine whether we want localisation on the application form, as we do not currently have the staffing capabilities to review arbitrary language submissions.

**Comment by hannahkane** [comment]
My instinct is that we shouldn't localise the application form until we've identified community members who can help review them OR perhaps we should note on the form that applications submitted in languages other than EN may take longer to be reviewed because we'll need to identify someone to help us with it on a case-by-case basis.

Would love input from @alicoding @jvallera @kgorr @amirad

**Comment by jvallera** [comment]
Agree with @hannahkane and think we should include a  note at the top. Instead of "may take longer" maybe we say "will take longer".

**Comment by KGorr** [comment]
What happens if we put that note and then we can't find anyone to help?

We have a list of about 20 folks who helped localize Web Lit 1 for us back in the winter. Perhaps we can reach out to them and see if they are interested to help if anything comes through. A handful of them have already asked me how they can help us with new projects - not just with localization, but I'm sure they would be thrilled to contribute. Let me know if I should clean up the list and/or reach out to them. Happy to help!

**Comment by hannahkane** [comment]
@KGorr - would love your input on [this doc](https://docs.google.com/document/d/1sLugqI1WMZTHHbO9W31sY2zQACcp6G2R-niys3OjCS4/edit#) where we're discussing that very idea.

**Comment by Pomax** [comment]
@hannahkane should this be moved into the backlog, pending discussions elsewhere?

**Comment by hannahkane** [comment]
Good call, @Pomax. Removing from milestone for now. I have a follow up scheduled with @KGorr and @jvallera for Wednesday.

**Comment by KGorr** [comment]
hmmm.... @hannahkane, I don't see anything on my calendar for Wed....

**Comment by hannahkane** [comment]
I was thinking of the Clubs Application review. Do you have that on your calendar?

**Comment by KGorr** [comment]
oh geez - I was looking at Thursday. Sorry @hannahkane! Yes, it's on my calendar!

**Comment by hannahkane** [comment]
Closing this ticket for now. Localization efforts will be focused on curriculum for the time being.
