### ISSUE TITLE
Localize new Clubs Pages?

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2051]
Hey @alicoding - question for you!

We're building out some new Clubs Pages - you can see the designers [here in redpen](https://redpen.io/pbcb2eda696626f5e7). We're wondering if we should set these pages up in a way so that they are localizable. If so, can you provide some guidance?

For now, I'm just hard-coding the English content.

cc @hannahkane

**Comment by alicoding** [comment]
They are okay for LTR localization and shouldn't be a problem since we are using Pontoon except hard-coding the English content will require a lot of work later to localize it. If you haven't started the implementation I would suggest do it from the beginning. Let me know if you need help figuring out that part.

**Comment by flukeout** [comment]
I've added all of the text strings already. If you can point me at an example in the existing code on the teach site of how you'd like it set up, I can start converting it.

**Comment by flukeout** [comment]
@alicoding showed me how to set up the localization, so I'll be doing that. Thanks!
