### ISSUE TITLE
Create workflow diagrams for curriculum localization

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2157]
Four diagrams to share with potential localizers and solicit feedback:

 - [ ] Form with source language content broken up into sections, and a field for you to submit your localization (@hannahkane)
 - [ ] Google doc with source language, make a copy, complete localization in the copy, migrate to Thimble or Github pages (@gideonthomas)
 - [ ] Remix a Thimble project (this one might be a screenshot)  (@hannahkane)
 - [ ] Pontoon (screenshot) (@gideonthomas)

**Comment by gideonthomas** [comment]
####Google Doc 
Prototype file for JustInMind: https://drive.google.com/a/mozilla.com/file/d/0BwCd-6qteGa8cWs5cEtWczQ4S1k/view?usp=sharing
How it looks: http://curriculuml10n.herokuapp.com/googledocs

**Comment by gideonthomas** [comment]
@hannahkane try that link again, it has the updated wireframes. I can walk you through it tomorrow and we can discuss any changes that need to be made.

**Comment by gideonthomas** [comment]
We've decided to change our approach to this a bit! We're going to start with some internal research about the current authoring experience and figuring out what needs to change and then suggesting more open-ended workflows that allow localizers to pick the final product's form (based on their skill set and comfort level) that is shown to the consumers of the activity.

For example, we can enable localization through Google Docs and that can be the finished product if localizers are not comfortable converting them to Github pages / Thimble Activities. Another localizer might decide to convert that to a more polished product (like github pages) since it is within their skill set.

This has a three-fold advantage:
1. It reduces conflation between the source-language authoring experience and the localization experience, thus allowing us to analyze each one's needs effectively.
2. It enables localizers to "create products" rather than just localize content since they are in control of what the consumer views subject to their understanding of cultural relevance and skill set.
3. It allows more collaboration between localizers to work together to create a final product that will be used in their community.

@hannahkane feel free to add/remove anything from this
