### ISSUE TITLE
Create survey for potential localizers

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2158]
See questions in [this doc](https://docs.google.com/document/d/1sLugqI1WMZTHHbO9W31sY2zQACcp6G2R-niys3OjCS4/edit#)

**Comment by gideonthomas** [comment]
Here's the form in its current state: https://docs.google.com/a/mozillafoundation.org/forms/d/1_Q6VjDI8boig2mI5OVrSk5ihnabMuAm28xcFL0qfGbI

Feel free to make edits!

**Comment by hannahkane** [comment]
The only thing I'm wondering about is if we should be more specific in the "Have you ever used Github" question at the end (which we ask of people who did not help with Web Lit Basics 1). I think maybe we're particularly curious about whether they've ever "committed code to a Github repository". What do you think?

Would be interested in @jvallera's and @ldecoursy's thoughts on this survey, too. Context: we're going to send this out to a group of folks (some of whom helped translate Web Lit 1) and will use the results to inform our decision about what localization workflow to use for the next round of curriculum localization. Gideon and I will also be conducting interviews with a subset of respondents.

**Comment by gideonthomas** [comment]
Maybe we should change that to a "comfort level" question then. Something like "How comfortable are you with using Github to contribute to a project?" maybe?

**Comment by hannahkane** [comment]
That sounds great. Maybe we could have an optional text field for them to explain their comment? I'm afraid we won't know what it means if the majority say "not comfortable."

**Comment by gideonthomas** [comment]
How does it look now?

**Comment by ldecoursy** [comment]
Does submitting content via Github issues count as "committing code?" The Web Lit Basics l10n project when we ran it involved people using a separate text editor then copy/pasting their content into a Github issue. For that last question, you might want to be more specific unless even some basic usage/understanding will do.

**Comment by ldecoursy** [comment]
Also @KGorr should have the list of folks that contributed to Web Lit 1 l10n if you need it ;)

**Comment by hannahkane** [comment]
I think the form looks good now. Should we add the Github Usage question as an optional question for those who said they were not comfortable during the Web Lit 1 localization process?

@gideonthomas - also wondering if we should add a question like, "Would you be willing to participate in a one-on-one conversation with a Mozilla staff member to share more about your ideas for or experiences with localization?"

That way we could use this as the pool for interviews.

**Comment by gideonthomas** [comment]
@hannahkane I just realized that there is no point in asking that question since google forms does not collect emails (so we will not know who said yes vs. who said no)

**Comment by jvallera** [comment]
I don't see any problem in asking for their name on the form. In which case the one-on-one questions can be useful to us.

**Comment by gideonthomas** [comment]
perfect! Will do

**Comment by gideonthomas** [comment]
@hannahkane how does it look now?

**Comment by hannahkane** [comment]
Survey looks perfect. Will check out email now. Thanks!

**Comment by hannahkane** [comment]
Just noting that the survey has been sent out to 22 people (one bounce back), and we have 7 responses so far! Leaving this ticket open, since we'll be summarizing the results at some point.

**Comment by jvallera** [comment]
that is great! Thanks. Looking forward to the results.

**Comment by jvallera** [comment]
Just want to note that I am finding content that has already been localized, so maybe we can add a question to the interview or follow up that asks if/what localized content already exists. 

For example, here are two activities translated into Italian: https://github.com/edovio/MozillaCagliariClub/tree/master/Activities

**Comment by gideonthomas** [comment]
## Survey Summary

### Facts
| Statistic | Data |
| :--- | :---: |
| Respondents | 13 |
| Preferred teaching format for activities | Using the webpage |
| Preferred authoring language | HTML |
| Respondents' open to being contacted for feedback | 100% |

### Analysis

1. __Finding__: While most respondents teach through the website, some prefer to print out the activity. <br>
__Analysis__: Need more input about why some prefer to print out the activity.<br><br>
2. __Finding__: Google Docs is overwhelmingly preferred over Thimble and Pontoon as a tool. <br>
__Analysis__: No context for what the tool will be used for was given and hence the result should only be analyzed in the context of the features they provide. While many are comfortable with HTML, there is a mixed response for the comfort level of Thimble which suggests improvements that can be made to the tool itself.<br><br>
3. __Finding__: Mixed results on the usage of Github for localization.<br>
__Analysis__: While only half the contributors were comfortable localizing Web Lit Basics I using Github, those who didn't contribute unequivocally said that they are comfortable using Github as a tool. This suggests a contradiction in the results that possibly needs further feedback to clarify. In the most simplistic case, this result is accurate suggesting that the instructions for that localization effort were the issue rather than the tool (Github) itself. On the other hand the tool itself might be too complex for its use in this scenario.

@hannahkane feel free to add/remove anything and close the issue accordingly.

**Comment by hannahkane** [comment]
Thanks for the summary, @gideonthomas.
