### ISSUE TITLE
Refer people to Mozilla Campus Clubs program

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2231]
The Participation team has recently launched a platform for [Mozilla Campus Clubs](https://campus.mozilla.community/), a program similar to Mozilla Clubs, but with a specific focus on college and university campuses. We will now begin referring people who are interested in starting a Mozilla Club on their college/university campus to this program.

To support this, we should identify key places on the Clubs page to educate users about the Campus Clubs program.

Below are some suggestions to start, but I'd welcome feedback from @taisdesouzalessa @sabrinang @xmatthewx and @jvallera

 * Add helper text to the "Where will you meet field" on the CC application form. ("Will your Club be on a college or university campus? Please apply at https://campus.mozilla.community/.")
 * Add copy to the "Find a Venue" section under "Elements of a Mozilla Club" on the "About Mozilla Clubs" tab. ("Clubs located on college or university campuses are part of the Mozilla Campus Clubs program.")

**Comment by jvallera** [comment]
Thanks and curious what everyone thinks. We definitely want campus clubs to apply separately through the campus club site, so I prefer to have it somewhere front an center or built into the application so it is not missed.

**Comment by LucyeoH** [comment]
+1 on the idea of having a place on the form that sends people to the campus application form if they indicate that they're at a university or college.

**Comment by hannahkane** [comment]
I think we likely need to have it *both* on the form and in one of the main content sections.

Maybe we add a pre-form question about whether the Club will be on a campus? That way we can re-direct ppl quickly without them having to spend time filling out the form unnecessarily.

**Comment by xmatthewx** [comment]
Ideally, we don't add too much friction or room for confusion within the form. We'll need a succinct unambiguous statement so we don't lose people. What's "on campus" include? School subsidized but in an off campus location? Unaffiliated with the school, but using a campus space?

Might be best to do this filtering outside the form. Anyone who slips thru could be referred from one program to the other. 

Or, could we create a single form that starts with the question about college affiliation, then splits to offer two different sets of questions? Not sure about google forms, but many form tools offer a feature to do that.

**Comment by LucyeoH** [comment]
Hey Matt,

The Club Captain (or captains) have to be a student registered in a
university or college and they have to give the information of their
university or college as well.

I think just: Are you currently a university or college student interested
in starting a club at your university/college?

**Comment by hannahkane** [comment]
Agreed that we don't want to create confusion with the form. I think adding a simple pre-step with Lucy's wording will help us direct people to the right form.

I don't think we should create a single form right now, as the form we have on the Learning site speaks directly to the teach-api, and we gain a lot of functionality from that.

**Comment by taisdesouzalessa** [comment]
I agree with the discussion here about asking the question about college affiliation as soon as possible because if this information is in the middle of the form, users can get frustrated (because they already started to fill in a form that may not be the correct one). 

About including this information on the page, what if we had a section called "Types of Mozilla Club" (not exactly this title - I am not good with copy - but something like that) inside the "About Mozilla Clubs tab"? Same hierarchy as "Elements of a Mozilla Club". We could add a brief description of the 2 types - the current one and the "Mozilla Campus Club" (with the link to the campus page). I think if we surface this with its own section it will be more visible to the audience. The challenge would be how to describe the "non Mozilla Campus Club", I think. 

Here is a quick drawing:
![mozilla-club](https://cloud.githubusercontent.com/assets/22157921/18763775/b7adb1e4-80c3-11e6-9122-8ed954705862.jpg)

**Comment by jvallera** [comment]
@taisdesouzalessa I agree about the form. and like your idea about having a section about "types of clubs" in the about section. I am guessing that several people go to our site and immediately click on "apply" in the banner and skip all the info below. In that case it would have to be in the application somewhere that tells them to go to the campus application or on the banner itself. 

Having a few sentences in the about section is definitely a good idea either way. thoughts?

**Comment by taisdesouzalessa** [comment]
Good point on people potentially missing the info if the information is deeper on the page, @jvallera. I was discussing ideas and options with @sabrinang. What if we do something like the image attached? It is important to have @Pomax's eyes on this since it may require some form logic - the green rectangles indicate the new sections
![user-flow](https://cloud.githubusercontent.com/assets/22157921/18854785/c188f9fc-8402-11e6-8a9d-fc71310bd94a.jpg)

**Comment by xmatthewx** [comment]
I really like @taisdesouzalessa's design of the Yes / No  question at the start of the application. This feels like the right moment and method to ask and redirect a visitor. 

The text link and the ad-like box below the signup are at risk of confusing people who are, in fact, in the right place. We've learned by testing content and CTAs for fundraising that prompting a visitor into taking action is very tricky and sensitive. I recommend that we remove those, rather than hedging our bets.

Do we have an existing problem with too many college-based club applicants? Or is this a preventative measure? If the campus clubs page will be advertised via Mozilla channels it will likely have much higher traffic and missed club opportunities than this page and its 300 weekly visitors. A link from there to here seems equally important.

<img width="794" alt="screenshot 2016-09-27 16 46 15" src="https://cloud.githubusercontent.com/assets/53411/18891141/f5ec2ce4-84d1-11e6-8b8d-b18ebdd5c80c.png">

<img width="782" alt="screenshot 2016-09-27 16 46 22" src="https://cloud.githubusercontent.com/assets/53411/18891166/0b16b468-84d2-11e6-9317-5513313f96c2.png">

**Comment by jvallera** [comment]
Great points @xmatthewx and I totally agree.  @LucyeoH can you add a link directing non-campus clubs to our site as well? see Matthews recommendation above.

**Comment by jvallera** [comment]
Follow up in relation to above comment: 

1. A link to Learning.mozilla/clubs is on the homepage of the [Campus Clubs](https://campus.mozilla.community/) site.

2. Campus Clubs now has the "are you currently a university student...." question at the beginning of their application form -- which directs them to learning site if they say no.

**Comment by hannahkane** [comment]
OK, so I think we've got it. We're going to with adding the initial weeding question to the form itself. I'm going to close this ticket, and open a new one, based on that decision. Thanks, all!

**Comment by hannahkane** [comment]
https://github.com/mozilla/learning.mozilla.org/issues/2275
