### ISSUE TITLE
update the "edit your club" modal to use the new form?

### ISSUE THREAD

**Issue by Pomax** [mozilla/learning.mozilla.org#2243]
Right now you can edit your club after filing an application (and presumably in perpetuity if we approve it), which uses a custom edit modal. However, we should probably determine which fields from the new application form are allowed to be modified after the fact, and which ones should not be, and present an edit form accordingly. Or even not allow people to edit their club after we approve it, needing to contact us for changes?

**Comment by hannahkane** [comment]
cc @jvallera and @KGorr for input on the above

**Comment by jvallera** [comment]
I think the only thing we would want clubs to be able to edit is their club name and location, but curious what KGorr thinks.

**Comment by KGorr** [comment]
Club name, Club location, latitude, longitude, club description - basically anything that shows up on the map that may change eventually (or they entered incorrectly to begin with, which happens). While we can do it manually, it would be really great if they can just do it themselves. Also, maybe owner email, because typos happen and we can't contact them.

**Comment by hannahkane** [comment]
We don't ask the user to tell us their latitude/longitude, right? That's derived from the location. @KGorr - Can you clarify why we'd want to let them adjust their lat/long?

We also don't ask for the owner's email address via the CC form, right? We pull that from their Webmaker account. I don't think we can let them edit that from the CC form.

**Comment by KGorr** [comment]
@hannahkane - I think you are right about the email address, but it goes back to a conversation we had awhile ago. Regardless of how we collect it, I run into typos and bounce backs quite often.

Regarding the lat/longitude - over the span of this year I've had to go in and manually update about 15-20 club coordinates because they didn't populate correctly. Or because it looks like there are 5 clubs all at the same location when they are actually spread out around the city (usually RCs send these types of requests). We can continue to do it manually if that is easier.

**Comment by hannahkane** [comment]
Thanks, Kristina. Agree that the email address issue is a problem. We'll have to solve it on the id.webmaker.org side, though (see https://github.com/mozilla/id.webmaker.org/issues/424). Solving it here would just create a conflict.

What's the process you use for adding lat/long? How do you decide what lat/long to enter? (Wondering if that's something we can expect users to do.)

**Comment by KGorr** [comment]
Sounds good @hannahkane. If a CC or RC tells me a club is showing up incorrectly on the map, I ask them to send me the lat/long and I'll make the change. So far, no one has said they can't provide the info. Once I have it, I update it manually and then ask them to verify it is showing correctly. Hope that helps!

**Comment by hannahkane** [comment]
I'm going to open up a separate ticket about the map/location issue.

For this ticket, @pomax, what do you think about offering an edit modal that allows the user to edit their Club name, url, Club description, and location?

**Comment by Pomax** [comment]
by location do you mean the venue, or the geographical location? Because the latter we only do to the "city" level so letting people change that would pretty much literally be "a different club" rather than a simple club edit. Venue would make sense though.

**Comment by hannahkane** [comment]
@Pomax - if you follow the conversation [above](https://github.com/mozilla/learning.mozilla.org/issues/2243#issuecomment-250275820), it seems that sometimes we have to change the actual location (not venue) of the Club. But it seems we've done this on the backend through lat/long, which we haven't exposed to users. Thinking on it now, I don't think we should expose that to users. Seems likely to confuse people.

Maybe we stick with Club name, url, and description for now, and continue to have staff make location changes on the backend.

**Comment by Pomax** [comment]
that sounds fair. I can start on that next week, or someone else can probably do a rejigger of the edit modal (Although we probably want to do this as a new modal, rather than a massaging of the preexisting code, since it's a combination of the old "add" modal and the old "edit" modal, and we want to remove the first, which is easiest to do by removing both and making a new edit modal instead)
