### ISSUE TITLE
Deployment question

### ISSUE THREAD

**Issue by mmmavis** [mozilla/learning.mozilla.org#2278]
Hey my lovely colleagues!

Since almost every MoFo eng is out today, I was asked to help make a new release to production. Everything on staging was good to go but after I clicked on the "Promote to production" button on Heroku our WIP credentials work got pushed to production. I'm curious to know what I did wrong, is there a step that I missed? I assume credentials work is toggled via env var and promoting to production shouldn't promote env vars???

/cc @Pomax @gvn @cadecairos @gideonthomas @hannahkane

**Comment by mmmavis** [comment]
`ENABLE_BADGES` flag isn't set on production - which means it's a falsy value - badges work shouldn't show on production. I'm not sure what caused the production. 👀

**Comment by cadecairos** [comment]
I'll need to familiarise myself the build process - But I'd wager that it is building environment variables right into the webpack outputs at build time, rather than fetching configuration at runtime. This breaks the promote button because it expects apps to conform to the [12 factor principles](12factor.net) and assumes it can just copy the build result over to the new environment (which results in staging environment variables being brought over into production.

**Comment by cadecairos** [comment]
To fix this, you'll need to go to the learning.mozilla.org app on Heroku, navigate to the deploy tab, and at the bottom there's a section for manual deploys. ensure "master" is selected and then hit the deploy button!

**Comment by mmmavis** [comment]
@cadecairos ahhhh now I remember there were emails sent out about this. We should definitely add a deployment section on README so people who work on multiple repos don't get confused. 😉

**Comment by mmmavis** [comment]
@cadecairos it gave me a Heroku Application Error .... 😭

**Comment by cadecairos** [comment]
### Update

The problem turned out to be a bug in the [babel-preset-es2015 package](https://github.com/babel/babel/issues/4592) that was introduced earlier today. A patch update was released to fix it, and we shouldn't have build issues anymore.
