### ISSUE TITLE
Right-side menu collapses when you click a tab

### ISSUE THREAD

**Issue by flukeout** [mozilla/learning.mozilla.org#2314]
The right side menu collapses if you click on any of the tabs within the Gigabit page or arrive at the page with one of the tabs in the address bar, like `/gigabit/portfolio`

![menu-collapse](https://cloud.githubusercontent.com/assets/25212/19203124/73ef0e12-8c8a-11e6-89b2-4f7619b6b720.gif)

**Comment by gvn** [comment]
This is actually the existing behavior for Clubs as well, so I'd like to tackle this as a follow-on if possible.

**Comment by hannahkane** [comment]
Pulling this out of Gigabit QA into regular queue

**Comment by aayushsanghavi** [comment]
@flukeout I'd like to take this up. How do I get started?

**Comment by aayushsanghavi** [comment]
@flukeout isn't this happening because the [handleTabChange event](https://github.com/mozilla/learning.mozilla.org/blob/master/pages/gigabit/index.jsx#L19) which occurs on clicking one of the tabs causes a new page to reload instead of changing the content internally?
Could you direct me towards a solution to this.

**Comment by Pomax** [comment]
This is caused by the `sub-nav-active` not getting set in https://github.com/mozilla/learning.mozilla.org/blob/master/components/sidebar/TopLevelNavItem.jsx#L41

**Comment by aayushsanghavi** [comment]
@Pomax thanks! I'll look into it and let you know if I have any questions.

**Comment by Pomax** [comment]
Note that the solution here will likely be making sure that tabs on pages preserve the page properties that the React code needs to automatically show the sidebar correctly, rather than making that an HTML element has a specific CSS class - the code can already do those things, it's likely a matter of making sure that specific React properties are preserved.

**Comment by aayushsanghavi** [comment]
@Pomax I've had little progress with it. The current state is that, after navigating to the gigabit index page, if I click on one of the tabs the sideNav stays but the gigabit tab in the sideNav loses the class "active" and then the sideNav becomes inactive again (as in the issue).
Also, there was one thing I found rather intriguing, the activeSubNav wasn't being set equal to subNavActive in https://github.com/mozilla/learning.mozilla.org/blob/master/components/sidebar/TopLevelNavItem.jsx#L23 even after entering the if statement. Instead, when I changed it to this.state.activeSubNav = subNavActive, I came to the state I just mentioned above.
I'm still looking into it. I'll take some time to figure out.

**Comment by Pomax** [comment]
Note that the code you link to *only* triggers when the page is loaded from the server for the specific URL you are on: we're using server-side rendering of pages to service specific requests, and the `routes.jsx` data informs the renderer which components should be nested how for specific URLs, which is then used to render those components to plain HTML for use while the react app loads for the user. So the HTML already has the "active" class (or: *should*) and then when the app starts to load up it checks to see which HTML element that active class is actually on.

So you might want to also see what happens when you only go straight to the gigabit page, and see where that active class is getting set. I'm pretty sure it's related to what comes rolling out of https://github.com/mozilla/learning.mozilla.org/blob/master/components/page.jsx#L48, which is the master "Page" function for determining what the current page class is. You may want to do a bit of digging there to see what it generates when the gigabit page is being loaded, and when tabs are being switched - I suspect that on the first go it finds the value explicitly encoded on https://github.com/mozilla/learning.mozilla.org/blob/master/pages/gigabit/index.jsx#L16 but when the tabs are active, it won't find anything.

That might be because the `getCurrentPageHandler` function finds the actually tab's inner component, in which case it will absolutely lose the className information because that function only checks one component, it does not check the entire chain of nested components to see if anyone might have a className that should be used.

**Comment by aayushsanghavi** [comment]
@Pomax I'll look into it today. Thanks for such an elaborate description.

**Comment by amarlearning** [comment]
@Pomax @aayushsanghavi Are you still working on it or should i take this ?

**Comment by aayushsanghavi** [comment]
@amarlearning go ahead, take it up.
