### ISSUE TITLE
Gigabit QA: Homepage spacing

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2327]
#2228 

Under 'The Gigabit Approach' - the content placement for the three focus areas content (specifically the content blocks should be centered under their respective icon) seems a tad bit off and a little too close to the main sidebar - can the padding be increased there at all (or can the content be shifted under the icons)?

**Comment by gvn** [comment]
The design indicates left alignment of the text. The icons may appear slightly off center because of this, but they are centered as designed...

Here's a visible border to help visualize:

<img width="706" alt="screen shot 2016-10-10 at 4 49 22 pm" src="https://cloud.githubusercontent.com/assets/206379/19254618/48fe84ee-8f0a-11e6-922b-777cf1d260a7.png">

**Comment by hannahkane** [comment]
Will close unless design (@flukeout) wants to reopen
