### ISSUE TITLE
edits to individual badge pages

### ISSUE THREAD

**Issue by anmechung** [mozilla/learning.mozilla.org#2377]
On each individual badge page (i.e. https://learning.mofostaging.net/en-US/badge/2215/connect) under badge requirements, change “Make or write something that demonstrates your understanding of any two or more of the following.” to “Complete the following three tasks and submit the required evidence.”

**Comment by Pomax** [comment]
this is a generic text, not tied to the "connect" badge (it's simply a template into which badge information is injected) so I assume we want the "three" part to actually be the number of tasks for each badge? (e.g. if a badge has two tasks, it should be "two", if it has seventeen, it should be "seventeen"?)

**Comment by IBGMozilla** [comment]
We need to add the four 21c badges to the mofostaging site as well the remaining four web literacy badges (right now only 10 are fitting on the site).

**Comment by IBGMozilla** [comment]
The "tasks" for the badges all are linked to the lesson plan and open there, however, the badge earner needs to scroll down the bottom of the page where it says, "IMLS Pilots: Earning Badges" as these are the steps for completing the task. Need the link from the badges/mofostaging to link directly to that part of the lesson plan page (IMLS Pilots) instead of taking them to the top of the page.

**Comment by anmechung** [comment]
@Pomax - sorry - missed this one and looping in @IBGMozilla.  It is generic text, not tied to any one badge. Each badge has 3 tasks.  None have less or more right now.
