### ISSUE TITLE
Remove reference to Open News fellowship

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2463]
...on [this page](https://learning.mozilla.org/en-US/opportunities)

The Become a Fellow section should include this sentence: Apply to join the next cohort of Science, Advocacy, and Developer Network Fellowships that best matches your interests and skills [remove "News"]

**Comment by aayushsanghavi** [comment]
@hannahkane I tried working on this but I got stuck. I removed all instances of newsLink from [this file](https://github.com/mozilla/learning.mozilla.org/blob/master/pages/opportunities/sectionlist.jsx), but turns out that doesn't really work. It gives an error on the console.
What would have caused this? How should I fix it?

**Comment by hannahkane** [comment]
@mmmavis - wondering if you'd be able to advise @aayushsanghavi?

**Comment by mmmavis** [comment]
@hannahkane for sure!

@aayushsanghavi do you remember what error you were seeing?

**Comment by aayushsanghavi** [comment]
Hello @mmmavis! Long time since Network Pulse.
So, regarding this issue, I removed all occurrences of the newsLink variable from [this file](https://github.com/mozilla/learning.mozilla.org/blob/master/pages/opportunities/sectionlist.jsx) but it seems that it didn't work. This is the error I am getting -
`[React Intl] Error formatting message: "become_a_fellow_message" for locale: "en-US"
Error: A value must be provided for: newsLink  index.js:694:17`
`[React Intl] Cannot format message: "become_a_fellow_message", using message source as fallback.`

**Comment by mmmavis** [comment]
Hi hi @aayushsanghavi 😃 Looks like we also need to remove it from https://github.com/mozilla/learning.mozilla.org/blob/master/locales/en-US/messages.properties#L133 . I think we are not watching changes on locale files... you will have to restart the server to see the result. Let me know if it works for you!

**Comment by aayushsanghavi** [comment]
Thanks @mmmavis! That worked.

**Comment by aayushsanghavi** [comment]
@hannahkane we're supposed to remove the open news link from all the locales right?

**Comment by hannahkane** [comment]
@aayushsanghavi - yes, please.

**Comment by aayushsanghavi** [comment]
@hannahkane done! Please have a look at the patch.

**Comment by hannahkane** [comment]
Thanks, @aayushsanghavi. I'll defer to @mmmavis and @gideonthomas to review your patch. They know more than me about how this works!
