### ISSUE TITLE
Add new cities to Gigabit site

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2464]
Add two new Gigabit cities (Eugene, OR and Lafayette, LA) to the following places:

<s>1. Add two dots on map on the main page (https://learning.mozilla.org/en-US/gigabit/). We will need to update once the new Portfolio Managers are hired, but we'd like the dots and the cities listed for now.</s> Moved to #2466
2. Update Apply page - https://learning.mozilla.org/en-US/gigabit/apply. (Changes to this page are in this Google doc - https://docs.google.com/a/mozilla.com/document/d/14HPDi6-x_ymhGJK_NuMlxtHQeXtlRWNgL0Np0FQMW68/edit?usp=sharing)
3. Can we also manually update the most recent blog post to this one - https://blog.mozilla.org/blog/2017/03/14/public-private-partnership-gigabit-innovation-internet-health/

**Comment by hannahkane** [comment]
Thanks, @jenntbeard. A few questions - 

For # 1 - so just the city name will be listed, with no contact info below (for now)? Could we say something to explain why they don't have contact info? (Maybe put them under a "Coming Soon" subheading?)

For # 2 - I'm a bit confused about what's new on that page - is it adding a second Type of Support chart to the page, or replacing the one that's currently there?

For # 3 - Can definitely update the link. Should the "See All Blog Posts" button link to https://blog.mozilla.org/blog/category/gigabit-fund/ instead of https://blog.mozilla.org/gigabit/?

**Comment by jenntbeard** [comment]
Hi Hannah,

#1 - correct - yes, "coming soon" would be great!
#2 -  Sorry, yes, that table is different (LF thought it was easier to just replace it completely for ease of following our logic/changes). The headers are not exactly the same, there is one less category and the text within the chart is updated. The rest of the changes to that page I tried to have tracked so you could see what we were doing to it. Happy to further clarify if needed.
#3 - Great, yes, that new link would be preferred, thank you!

**Comment by hannahkane** [comment]
Thanks, @jenntbeard. Now that I have edit access to the doc, I see all the changes! (When I had view only access, I couldn't see the edits! Makes much more sense now.)

Putting item 1 in a [separate ticket](https://github.com/mozilla/learning.mozilla.org/issues/2466) since it requires a designer.

Will file a PR for the rest shortly.

**Comment by jenntbeard** [comment]
Fantastic, thanks so much! (Sorry about the permissions setting - I've been on the road for 9 days and the settings aren't that apparent on my phone.) :)
