### ISSUE TITLE
Update Gigabit Cities Map

### ISSUE THREAD

**Issue by hannahkane** [mozilla/learning.mozilla.org#2466]
- [ ] Add two dots on map on the [main Gigabit page](https://learning.mozilla.org/en-US/gigabit/) representing Eugene, OR and Lafayette, LA. 
- [ ] Add these cities to the list on the right, under a "Coming Soon" heading (we don't yet have contact info for these cities, so it will just be the names)

**Comment by hannahkane** [comment]
@sabrinang - would you have time to help with this ticket?

**Comment by sabrinang** [comment]
Updated map on gdrive: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eNUlCNFRGd2ppeVU/view?usp=sharing

Instead of a coming soon heading that visually separate this section further down the page we can have 3-columns for all cities and have coming soon cities such as Eugene and Lafayette to be appended to the list but with a small "Coming Soon" label beneath it and it would be the same size as the name but in grey. 
<img width="912" alt="image" src="https://cloud.githubusercontent.com/assets/2492510/25155246/f489fa68-2448-11e7-92e5-103062496c80.png">

**Comment by hannahkane** [comment]
Thanks, @sabrinang. I think this looks great! @jenntbeard - what do you think?

**Comment by jenntbeard** [comment]
Looks great!

**Comment by hannahkane** [comment]
@alanmoo - this is the ticket I was hoping you could help with. If you look at the image Sabrina dropped in above, you'll see it's replacing the map graphic, but also changing the way the cities are listed on the page, since we now have 5 instead of 3.

**Comment by alanmoo** [comment]
I'll do this tomorrow unless any contributors take it (I posted in chat)

**Comment by flukeout** [comment]
Doing now
