### ISSUE TITLE
Updates to the Gigabit Terms & Conditions page

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/learning.mozilla.org#2524]
Hello! We have some updates to the Terms & Conditions page (https://learning.mozilla.org/en-US/gigabit/apply/terms) that we need to be made as soon as possible. They are technically still in legal review, but since the LOI is technically open, we want to make sure that people reference as up-to-date a version as possible. (Fingers crossed that Michael won't have anything too major.) 

The changes/updates have been made and are highlighted in this document (let me know if you have any questions):
https://docs.google.com/document/d/1JcHwvcFjZkFsY0tEyBz1MoRIAaSII_XmAG6Y4n4G87s/edit#heading=h.tphnj2r70grp

**Comment by hannahkane** [comment]
Hey @jenntbeard - I dropped some comments in the doc. Could you take a look, before we go ahead and make these updates? Thanks!

**Comment by jenntbeard** [comment]
Yes, will do!

**Comment by hannahkane** [comment]
OK, @jenntbeard and @LindseyFrost - I've made all of the updates in the doc as of today. Let me know if we should push it live.

Notes:
 * There had been a sentence on the site, "For additional guidance, please use this [application guide.](https://docs.google.com/document/d/1cxe4vKigqt9gnuxy8x5U7hzh_svdZvAOqj3VZCLdFZI/edit)” that I removed because it wasn't in the latest doc, but I put a comment in the doc just to confirm that you don't want it. It seemed sort of important, and there were several discrepancies between the doc and the live version of the site, so I just wanted to double check.
 * I did not add this, per Lindsey's comment in the doc: "Indirect costs should be limited to 10% of the overall budget. No funds may be allocated for the purchase of alcoholic beverages. International spending and travel must be approved by Mozilla staff.

**Comment by jenntbeard** [comment]
It looks good to me, I will check with @LindseyFrost @lindseyinCHA.

**Comment by LindseyInCHA** [comment]
Looks great to me @hannahkane 

* Agree that we need to keep that sentence. I updated the link in the google doc.  Thank you!

* Waiting on legal review of those two sentences, so will keep you in the loop.  Agree not to add now.  


Thank you!

**Comment by hannahkane** [comment]
Thanks, both. I've filed a pull request. Hopefully these changes will be live soon.

**Comment by jenntbeard** [comment]
Great, thanks, Hannah!
